services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    volumes:
      - ./apps/backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=adpay
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET_KEY=secret

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=adpay
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
